name: Register Webhook URL
on:
  workflow_dispatch:
    inputs:
      webhookUrl:
        description: 'Register webhook URL for Vipps payment events'
        required: true
jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Get access token
        id: get_token
        run: |
          const httpm = require('@actions/http-client');
          let http = new httpm.HttpClient('vipps-action');
          let res = await http.get('${{ secrets.VIPPS_API_URL }}/accessToken/get', {
            headers: {
              'client_id': '${{ secrets.CLIENT_ID }}',
              'client_secret': '${{ secrets.CLIENT_SECRET }}',
              'Ocp-Apim-Subscription-Key': '${{ secrets.OCP_APIM_SUBSCRIPTION_KEY }}',
              'Merchant-Serial-Number': '${{ secrets.MERCHANT_SERIAL_NUMBER }}',
              'Vipps-System-Name': 'Github Action',
              'Vipps-System-Version': '2.0',
              'Vipps-System-Plugin-Name': 'Github Action Vipps Payment Webhook',
              'Vipps-System-Plugin-Version': '1.0'
            }
          });
          let token = res.result;
          console.log(`::set-output name=token::${token}`);
        env:
          NODE_PATH: ${{ runner.workspace }}/node_modules

      - name: Register webhook
        run: |
          const httpm = require('@actions/http-client');
          let http = new httpm.HttpClient('vipps-action');
          let payload = {
            url: '${{ github.event.inputs.webhookUrl }}',
            events: ['epayments.payment.captured.v1']
          };
          let res = await http.post('${{ secrets.VIPPS_API_URL }}/webhooks/v1/webhooks', JSON.stringify(payload), {
            headers: {
              'Authorization': `Bearer ${{ steps.get_token.outputs.token }}`,
              'Content-Type': 'application/json'
            }
          });
          console.log(res.result);
        env:
          NODE_PATH: ${{ runner.workspace }}/node_modules